using Iserik.FaFOptimiser.Catalog;
using Iserik.FaFOptimiser.Solver;
using Mafi;
using Mafi.Core;
using Mafi.Core.Buildings.Settlements;
using Mafi.Core.Population; // Required for FoodProto & FoodCategoryProto
using Mafi.Core.Products;
using Mafi.Core.PropertiesDb;
using Mafi.Core.Prototypes;
using Mafi.Unity.UiToolkit.Library;
using System;
using System.Collections.Generic;

namespace Iserik.FaFOptimiser.Services
{
    public class DemandStateManager
    {
        private readonly ProductionChainService m_chainService;
        public readonly RecipeCatalog m_catalog;

        private readonly SettlementsManager m_settlementsManager;
        private readonly IPropertiesDb m_propertiesDb;
        private readonly ProtosDb m_protosDb;

        public OptimizationResult LatestResult { get; set; }

        // Dynamic Lookup Table: ProductId -> (CategoryName, BaseDemand)
        private readonly Dictionary<string, (string Category, float BaseDemand)> m_dynamicFoodStats
            = new Dictionary<string, (string, float)>();

        // User's direct requests
        public Dictionary<ProductProto, Fix32> DirectCropDemands { get; } = new Dictionary<ProductProto, Fix32>();
        public Dictionary<ProductProto, Fix32> ManufacturedDemands { get; } = new Dictionary<ProductProto, Fix32>();

        // --- UI Pending Selections (Segregated for Serialization & State Management) ---
        public ProductProto PendingNewCrop { get; set; }
        public ProductProto PendingNewProduct { get; set; }

        // Active chains mapped to the manufactured foods
        public Dictionary<ProductProto, ResolvedChain> SelectedChains { get; } = new Dictionary<ProductProto, ResolvedChain>();

        // The grand total of all required crops (Direct + Chain requirements)
        public Dictionary<ProductProto, Fix32> AggregateCropDemands { get; private set; } = new Dictionary<ProductProto, Fix32>();

        private readonly GreedyByproductOptimizer m_byproductOptimizer;

        // UI Event to trigger a redraw when numbers change
        public event Action OnDemandsUpdated;

        // The leftover byproducts generated by the factory that exceed demand
        public Dictionary<ProductProto, Fix32> CurrentSurpluses { get; private set; } = new Dictionary<ProductProto, Fix32>();

        // Add this right next to your SelectedChains dictionary
        public Dictionary<ProductProto, ResolvedChain> PinnedChains { get; } = new Dictionary<ProductProto, ResolvedChain>();

        public bool IsManualOverrideEnabled { get; set; } = false;

        public DemandStateManager(
            ProductionChainService chainService,
            GreedyByproductOptimizer byproductOptimizer, // <-- NEW
            RecipeCatalog catalog,
            SettlementsManager settlementsManager,
            IPropertiesDb propertiesDb,
            ProtosDb protosDb)
        {
            
            this.m_chainService = chainService;
            this.m_byproductOptimizer = byproductOptimizer;
            this.m_catalog = catalog;
            this.m_settlementsManager = settlementsManager;
            this.m_propertiesDb = propertiesDb;
            this.m_protosDb = protosDb;

            // Build the stats dictionary immediately when the mod loads!
            BuildDynamicFoodStats();
        }

        private void BuildDynamicFoodStats()
        {
            foreach (FoodProto foodProto in this.m_protosDb.All<FoodProto>())
            {
                string catName = foodProto.FoodCategory.Id.Value;
                float baseDemand = foodProto.GetConsumedQuantityFromPopDays(3000, Percent.Hundred).Value.ToFloat();
                this.m_dynamicFoodStats[foodProto.Product.Id.Value] = (catName, baseDemand);
            }
        }

        public void LoadFromSettlement(SettlementTelemetryService telemetry)
        {
            var unifiedDemand = telemetry.GetUnifiedFoodDemand();

            this.DirectCropDemands.Clear();
            this.ManufacturedDemands.Clear();
            this.SelectedChains.Clear();

            foreach (var kvp in unifiedDemand)
            {
                ProductProto product = kvp.Key;
                FoodDemandMetrics metrics = kvp.Value;

                Fix32 amount = metrics.EstimatedMonthlyConsumption;

                if (amount > Fix32.Zero || metrics.IsConfiguredInMarket)
                {
                    SetDemandAmount(product, amount, triggerUpdate: false);
                }
            }

            RecalculateTheoreticalDemand();
        }

        public void SetDemandAmount(ProductProto product, Fix32 amount, bool triggerUpdate = true)
        {
            if (this.m_catalog.IsCrop(product))
            {
                if (amount > Fix32.Zero) this.DirectCropDemands[product] = amount;
                else this.DirectCropDemands.Remove(product);
            }
            else
            {
                if (amount > Fix32.Zero)
                {
                    this.ManufacturedDemands[product] = amount;

                    var chains = this.m_chainService.GetAlternativeChains(product, amount);
                    if (chains.Count > 0)
                    {
                        this.SelectedChains[product] = chains[0];
                    }
                }
                else
                {
                    this.ManufacturedDemands.Remove(product);
                    this.SelectedChains.Remove(product);
                }
            }

            if (triggerUpdate) RecalculateTheoreticalDemand();
        }

        public void SetSelectedChain(ProductProto product, ResolvedChain chain)
        {
            if (this.ManufacturedDemands.ContainsKey(product))
            {
                // 1. Save it to the memory bank!
                this.PinnedChains[product] = chain;

                // 2. We MUST trigger a full global recalculation because 
                // changing a chain completely changes the byproduct pool!
                RecalculateTheoreticalDemand();
            }
        }

        private void RecalculateAggregateCrops()
        {
            this.AggregateCropDemands.Clear();

            foreach (var kvp in this.DirectCropDemands)
            {
                AddCropDemand(kvp.Key, kvp.Value);
            }

            foreach (var chain in this.SelectedChains.Values)
            {
                var cropsNeeded = chain.GetRequiredCrops();
                foreach (var kvp in cropsNeeded)
                {
                    AddCropDemand(kvp.Key, kvp.Value);
                }
            }

            OnDemandsUpdated?.Invoke();
        }

        private void AddCropDemand(ProductProto crop, Fix32 amount)
        {
            if (this.AggregateCropDemands.ContainsKey(crop))
            {
                this.AggregateCropDemands[crop] += amount;
            }
            else
            {
                this.AggregateCropDemands[crop] = amount;
            }
        }

        public void RecalculateTheoreticalDemand()
        {
            if (IsManualOverrideEnabled)
            {
                RecalculateAggregateCrops();
                return;
            }

            int totalPopulation = this.m_settlementsManager.GetTotalPopulation();
            if (totalPopulation <= 0) return;

            Fix32 globalMultiplier = this.m_propertiesDb.GetProperty(IdsCore.PropertyIds.FoodConsumptionMultiplier).Value.ToFix32();

            var activeFoods = new List<ProductProto>();
            activeFoods.AddRange(this.ManufacturedDemands.Keys);
            activeFoods.AddRange(this.DirectCropDemands.Keys);

            var activeCategories = new Dictionary<string, int>();

            foreach (var food in activeFoods)
            {
                if (this.m_dynamicFoodStats.TryGetValue(food.Id.Value, out var stats))
                {
                    if (activeCategories.ContainsKey(stats.Category))
                        activeCategories[stats.Category]++;
                    else
                        activeCategories[stats.Category] = 1;
                }
            }

            int Nc = activeCategories.Count;
            if (Nc == 0) return;

            Fix32 popMultiplier = Fix32.FromFloat(totalPopulation / 100f);

            // 1. Gather all raw demands into a temporary dictionary
            // 1. Gather all raw demands into a temporary dictionary
            var rawDemandsToOptimize = new Dictionary<ProductProto, Fix32>();

            foreach (var food in activeFoods)
            {
                // IS IT A HUMAN FOOD?
                if (this.m_dynamicFoodStats.TryGetValue(food.Id.Value, out var stats))
                {
                    int N = activeCategories[stats.Category];
                    float finalDemandFloat = stats.BaseDemand / (Nc * N);
                    Fix32 finalDemand = Fix32.FromFloat(finalDemandFloat) * popMultiplier * globalMultiplier;

                    if (this.m_catalog.IsCrop(food))
                    {
                        this.DirectCropDemands[food] = finalDemand;
                    }
                    else
                    {
                        this.ManufacturedDemands[food] = finalDemand;
                        rawDemandsToOptimize[food] = finalDemand; // Add to batch
                    }
                }
                // IT IS NOT A HUMAN FOOD (e.g., Animal Feed, Flour)
                else
                {
                    // Do not apply population scaling. Just use the existing user-set demand 
                    // and push it directly to the optimizer batch!
                    if (!this.m_catalog.IsCrop(food) && this.ManufacturedDemands.TryGetValue(food, out Fix32 manualDemand))
                    {
                        rawDemandsToOptimize[food] = manualDemand;
                    }
                }
            }

            // 2. Hand the batch AND THE PINNED CHAINS to the Two-Pass Optimizer
            GreedyOptimizationResult optimizedData = this.m_byproductOptimizer.RunTwoPassOptimization(rawDemandsToOptimize, this.PinnedChains);

            // 3. Save the results back to the state manager
            this.SelectedChains.Clear();
            foreach (var kvp in optimizedData.FinalChains)
            {
                // Link the chain to the product in the state manager
                this.SelectedChains[kvp.Key] = kvp.Value;

                // Ensure the chain knows it is satisfying this specific product
                kvp.Value.AddSatisfiedProduct(kvp.Key);
            }

            // 4. Save the Final Surpluses so the UI can display them
            this.CurrentSurpluses = optimizedData.FinalSurpluses;

            RecalculateAggregateCrops();
        }


    }
}